replicaCount: 1
bridge:
  env:
    LOG_LEVEL: INFO
enclave:
  image:
    tag: 30ba023
  env:
    ENCLAVE_CPU_COUNT: "2"
    ENCLAVE_MEMORY_SIZE: "1000"
    ENCLAVE_CID: "16"
    ENCLAVE_DEBUG_MODE: null
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone, https://admin.team.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: "50"
    external-dns.alpha.kubernetes.io/hostname: odometer-attester.dimo.zone
  hosts:
    - host: odometer-attester.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
