// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/.well-known/nsm-attestation": {
            "get": {
                "description": "Get the Nitro Security Module attestation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attestation"
                ],
                "summary": "Get NSM attestation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nitrite.Result"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_app.codeResp"
                        }
                    }
                }
            }
        },
        "/keys": {
            "get": {
                "description": "Get the public key and Ethereum address of the controller",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Get public keys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_app.KeysResponse"
                        }
                    }
                }
            }
        },
        "/vehicle/{tokenId}": {
            "get": {
                "description": "Get information about a specific vehicle by token ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "Get vehicle information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.GraphQLResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_app.codeResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_app.codeResp"
                        }
                    }
                }
            }
        },
        "/vehicle/{tokenId}/odometer": {
            "get": {
                "description": "Get the odometer reading for a specific vehicle by token ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "Get vehicle odometer reading",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cloudevent.CloudEvent-encoding_json_RawMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_app.codeResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_app.codeResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "big.Int": {
            "type": "object"
        },
        "cloudevent.CloudEvent-encoding_json_RawMessage": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains domain-specific information about the event.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "datacontenttype": {
                    "description": "DataContentType is an optional MIME type for the data field. We almost\nalways serialize to JSON and in that case this field is implicitly\n\"application/json\".",
                    "type": "string"
                },
                "dataschema": {
                    "description": "DataSchema is an optional URI pointing to a schema for the data field.",
                    "type": "string"
                },
                "dataversion": {
                    "description": "DataVersion is the version of the data type.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is an identifier for the event. The combination of ID and Source must\nbe unique.",
                    "type": "string"
                },
                "producer": {
                    "description": "Producer is a specific instance, process or device that creates the data structure describing the CloudEvent.",
                    "type": "string"
                },
                "source": {
                    "description": "Source is the context in which the event happened. In a distributed system it might consist of multiple Producers.",
                    "type": "string"
                },
                "specversion": {
                    "description": "SpecVersion is the version of CloudEvents specification used.\nThis is always hardcoded \"1.0\".",
                    "type": "string"
                },
                "subject": {
                    "description": "Subject is an optional field identifying the subject of the event within\nthe context of the event producer. In practice, we always set this.",
                    "type": "string"
                },
                "time": {
                    "description": "Time is an optional field giving the time at which the event occurred. In\npractice, we always set this.",
                    "type": "string"
                },
                "type": {
                    "description": "Type describes the type of event. It should generally be a reverse-DNS\nname.",
                    "type": "string"
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.GraphQLResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.dataField"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.graphQLError"
                    }
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.dataField": {
            "type": "object",
            "properties": {
                "vehicle": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.vehicleField"
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.definitionResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.nullableString"
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.deviceResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "imei": {
                    "type": "string"
                },
                "manufacturer": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.manufacturer"
                },
                "tokenId": {
                    "type": "integer"
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.graphQLError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.manufacturer": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.nullableString": {
            "type": "object"
        },
        "github_com_DIMO-Network_odometer-attester_internal_client_identity.vehicleField": {
            "type": "object",
            "properties": {
                "aftermarketDevice": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.deviceResponse"
                },
                "definition": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.definitionResponse"
                },
                "syntheticDevice": {
                    "$ref": "#/definitions/github_com_DIMO-Network_odometer-attester_internal_client_identity.deviceResponse"
                }
            }
        },
        "internal_app.KeysResponse": {
            "type": "object",
            "properties": {
                "ethereumAddress": {
                    "type": "string"
                },
                "publicKey": {
                    "type": "string"
                }
            }
        },
        "internal_app.codeResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "net.IPNet": {
            "type": "object",
            "properties": {
                "ip": {
                    "description": "network number",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "mask": {
                    "description": "network mask",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "nitrite.Document": {
            "type": "object",
            "properties": {
                "cabundle": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "certificate": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "digest": {
                    "type": "string"
                },
                "module_id": {
                    "type": "string"
                },
                "nonce": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pcrs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "public_key": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "type": "integer"
                },
                "user_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "nitrite.Result": {
            "type": "object",
            "properties": {
                "certificates": {
                    "description": "Certificates contains all of the certificates except the root.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/x509.Certificate"
                    }
                },
                "cose_sign1": {
                    "description": "COSESign1 contains the COSE Signature Structure which was used to\ncalculate the ` + "`" + `Signature` + "`" + `.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "document": {
                    "description": "Document contains the attestation document.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/nitrite.Document"
                        }
                    ]
                },
                "payload": {
                    "description": "Payload section from the COSE Sign1 payload.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "protected": {
                    "description": "Protected section from the COSE Sign1 payload.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "signature": {
                    "description": "Signature section from the COSE Sign1 payload.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "signature_ok": {
                    "description": "SignatureOK designates if the signature was OK (but certificate could be\ninvalid, not trusted, expired, etc.)",
                    "type": "boolean"
                },
                "unprotected": {
                    "description": "Unprotected section from the COSE Sign1 payload.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "pkix.AttributeTypeAndValue": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "value": {}
            }
        },
        "pkix.Extension": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "boolean"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "pkix.Name": {
            "type": "object",
            "properties": {
                "commonName": {
                    "type": "string"
                },
                "country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extraNames": {
                    "description": "ExtraNames contains attributes to be copied, raw, into any marshaled\ndistinguished names. Values override any attributes with the same OID.\nThe ExtraNames field is not populated when parsing, see Names.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkix.AttributeTypeAndValue"
                    }
                },
                "locality": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "names": {
                    "description": "Names contains all parsed attributes. When parsing distinguished names,\nthis can be used to extract non-standard attributes that are not parsed\nby this package. When marshaling to RDNSequences, the Names field is\nignored, see ExtraNames.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkix.AttributeTypeAndValue"
                    }
                },
                "organization": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "organizationalUnit": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "postalCode": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "province": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "serialNumber": {
                    "type": "string"
                },
                "streetAddress": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "url.URL": {
            "type": "object",
            "properties": {
                "forceQuery": {
                    "description": "append a query ('?') even if RawQuery is empty",
                    "type": "boolean"
                },
                "fragment": {
                    "description": "fragment for references, without '#'",
                    "type": "string"
                },
                "host": {
                    "description": "host or host:port (see Hostname and Port methods)",
                    "type": "string"
                },
                "omitHost": {
                    "description": "do not emit empty host (authority)",
                    "type": "boolean"
                },
                "opaque": {
                    "description": "encoded opaque data",
                    "type": "string"
                },
                "path": {
                    "description": "path (relative paths may omit leading slash)",
                    "type": "string"
                },
                "rawFragment": {
                    "description": "encoded fragment hint (see EscapedFragment method)",
                    "type": "string"
                },
                "rawPath": {
                    "description": "encoded path hint (see EscapedPath method)",
                    "type": "string"
                },
                "rawQuery": {
                    "description": "encoded query values, without '?'",
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                },
                "user": {
                    "description": "username and password information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/url.Userinfo"
                        }
                    ]
                }
            }
        },
        "url.Userinfo": {
            "type": "object"
        },
        "x509.Certificate": {
            "type": "object",
            "properties": {
                "authorityKeyId": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "basicConstraintsValid": {
                    "description": "BasicConstraintsValid indicates whether IsCA, MaxPathLen,\nand MaxPathLenZero are valid.",
                    "type": "boolean"
                },
                "crldistributionPoints": {
                    "description": "CRL Distribution Points",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dnsnames": {
                    "description": "Subject Alternate Name values. (Note that these values may not be valid\nif invalid values were contained within a parsed certificate. For\nexample, an element of DNSNames may not be a valid DNS domain name.)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "emailAddresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "excludedDNSDomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "excludedEmailAddresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "excludedIPRanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/net.IPNet"
                    }
                },
                "excludedURIDomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extKeyUsage": {
                    "description": "Sequence of extended key usages.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/x509.ExtKeyUsage"
                    }
                },
                "extensions": {
                    "description": "Extensions contains raw X.509 extensions. When parsing certificates,\nthis can be used to extract non-critical extensions that are not\nparsed by this package. When marshaling certificates, the Extensions\nfield is ignored, see ExtraExtensions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkix.Extension"
                    }
                },
                "extraExtensions": {
                    "description": "ExtraExtensions contains extensions to be copied, raw, into any\nmarshaled certificates. Values override any extensions that would\notherwise be produced based on the other fields. The ExtraExtensions\nfield is not populated when parsing certificates, see Extensions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkix.Extension"
                    }
                },
                "inhibitAnyPolicy": {
                    "description": "InhibitAnyPolicy and InhibitAnyPolicyZero indicate the presence and value\nof the inhibitAnyPolicy extension.\n\nThe value of InhibitAnyPolicy indicates the number of additional\ncertificates in the path after this certificate that may use the\nanyPolicy policy OID to indicate a match with any other policy.\n\nWhen parsing a certificate, a positive non-zero InhibitAnyPolicy means\nthat the field was specified, -1 means it was unset, and\nInhibitAnyPolicyZero being true mean that the field was explicitly set to\nzero. The case of InhibitAnyPolicy==0 with InhibitAnyPolicyZero==false\nshould be treated equivalent to -1 (unset).",
                    "type": "integer"
                },
                "inhibitAnyPolicyZero": {
                    "description": "InhibitAnyPolicyZero indicates that InhibitAnyPolicy==0 should be\ninterpreted as an actual maximum path length of zero. Otherwise, that\ncombination is interpreted as InhibitAnyPolicy not being set.",
                    "type": "boolean"
                },
                "inhibitPolicyMapping": {
                    "description": "InhibitPolicyMapping and InhibitPolicyMappingZero indicate the presence\nand value of the inhibitPolicyMapping field of the policyConstraints\nextension.\n\nThe value of InhibitPolicyMapping indicates the number of additional\ncertificates in the path after this certificate that may use policy\nmapping.\n\nWhen parsing a certificate, a positive non-zero InhibitPolicyMapping\nmeans that the field was specified, -1 means it was unset, and\nInhibitPolicyMappingZero being true mean that the field was explicitly\nset to zero. The case of InhibitPolicyMapping==0 with\nInhibitPolicyMappingZero==false should be treated equivalent to -1\n(unset).",
                    "type": "integer"
                },
                "inhibitPolicyMappingZero": {
                    "description": "InhibitPolicyMappingZero indicates that InhibitPolicyMapping==0 should be\ninterpreted as an actual maximum path length of zero. Otherwise, that\ncombination is interpreted as InhibitAnyPolicy not being set.",
                    "type": "boolean"
                },
                "ipaddresses": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "isCA": {
                    "type": "boolean"
                },
                "issuer": {
                    "$ref": "#/definitions/pkix.Name"
                },
                "issuingCertificateURL": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "keyUsage": {
                    "$ref": "#/definitions/x509.KeyUsage"
                },
                "maxPathLen": {
                    "description": "MaxPathLen and MaxPathLenZero indicate the presence and\nvalue of the BasicConstraints' \"pathLenConstraint\".\n\nWhen parsing a certificate, a positive non-zero MaxPathLen\nmeans that the field was specified, -1 means it was unset,\nand MaxPathLenZero being true mean that the field was\nexplicitly set to zero. The case of MaxPathLen==0 with MaxPathLenZero==false\nshould be treated equivalent to -1 (unset).\n\nWhen generating a certificate, an unset pathLenConstraint\ncan be requested with either MaxPathLen == -1 or using the\nzero value for both MaxPathLen and MaxPathLenZero.",
                    "type": "integer"
                },
                "maxPathLenZero": {
                    "description": "MaxPathLenZero indicates that BasicConstraintsValid==true\nand MaxPathLen==0 should be interpreted as an actual\nmaximum path length of zero. Otherwise, that combination is\ninterpreted as MaxPathLen not being set.",
                    "type": "boolean"
                },
                "notAfter": {
                    "description": "Validity bounds.",
                    "type": "string"
                },
                "notBefore": {
                    "description": "Validity bounds.",
                    "type": "string"
                },
                "ocspserver": {
                    "description": "RFC 5280, 4.2.2.1 (Authority Information Access)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "permittedDNSDomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "permittedDNSDomainsCritical": {
                    "description": "Name constraints",
                    "type": "boolean"
                },
                "permittedEmailAddresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "permittedIPRanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/net.IPNet"
                    }
                },
                "permittedURIDomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "policies": {
                    "description": "Policies contains all policy identifiers included in the certificate.\nSee CreateCertificate for context about how this field and the PolicyIdentifiers field\ninteract.\nIn Go 1.22, encoding/gob cannot handle and ignores this field.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/x509.OID"
                    }
                },
                "policyIdentifiers": {
                    "description": "PolicyIdentifiers contains asn1.ObjectIdentifiers, the components\nof which are limited to int32. If a certificate contains a policy which\ncannot be represented by asn1.ObjectIdentifier, it will not be included in\nPolicyIdentifiers, but will be present in Policies, which contains all parsed\npolicy OIDs.\nSee CreateCertificate for context about how this field and the Policies field\ninteract.",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "policyMappings": {
                    "description": "PolicyMappings contains a list of policy mappings included in the certificate.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/x509.PolicyMapping"
                    }
                },
                "publicKey": {},
                "publicKeyAlgorithm": {
                    "$ref": "#/definitions/x509.PublicKeyAlgorithm"
                },
                "raw": {
                    "description": "Complete ASN.1 DER content (certificate, signature algorithm and signature).",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rawIssuer": {
                    "description": "DER encoded Issuer",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rawSubject": {
                    "description": "DER encoded Subject",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rawSubjectPublicKeyInfo": {
                    "description": "DER encoded SubjectPublicKeyInfo.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rawTBSCertificate": {
                    "description": "Certificate part of raw ASN.1 DER content.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "requireExplicitPolicy": {
                    "description": "RequireExplicitPolicy and RequireExplicitPolicyZero indicate the presence\nand value of the requireExplicitPolicy field of the policyConstraints\nextension.\n\nThe value of RequireExplicitPolicy indicates the number of additional\ncertificates in the path after this certificate before an explicit policy\nis required for the rest of the path. When an explicit policy is required,\neach subsequent certificate in the path must contain a required policy OID,\nor a policy OID which has been declared as equivalent through the policy\nmapping extension.\n\nWhen parsing a certificate, a positive non-zero RequireExplicitPolicy\nmeans that the field was specified, -1 means it was unset, and\nRequireExplicitPolicyZero being true mean that the field was explicitly\nset to zero. The case of RequireExplicitPolicy==0 with\nRequireExplicitPolicyZero==false should be treated equivalent to -1\n(unset).",
                    "type": "integer"
                },
                "requireExplicitPolicyZero": {
                    "description": "RequireExplicitPolicyZero indicates that RequireExplicitPolicy==0 should be\ninterpreted as an actual maximum path length of zero. Otherwise, that\ncombination is interpreted as InhibitAnyPolicy not being set.",
                    "type": "boolean"
                },
                "serialNumber": {
                    "$ref": "#/definitions/big.Int"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "signatureAlgorithm": {
                    "$ref": "#/definitions/x509.SignatureAlgorithm"
                },
                "subject": {
                    "$ref": "#/definitions/pkix.Name"
                },
                "subjectKeyId": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "unhandledCriticalExtensions": {
                    "description": "UnhandledCriticalExtensions contains a list of extension IDs that\nwere not (fully) processed when parsing. Verify will fail if this\nslice is non-empty, unless verification is delegated to an OS\nlibrary which understands all the critical extensions.\n\nUsers can access these extensions using Extensions and can remove\nelements from this slice if they believe that they have been\nhandled.",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "unknownExtKeyUsage": {
                    "description": "Encountered extended key usages unknown to this package.",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "uris": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/url.URL"
                    }
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "x509.ExtKeyUsage": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13
            ],
            "x-enum-varnames": [
                "ExtKeyUsageAny",
                "ExtKeyUsageServerAuth",
                "ExtKeyUsageClientAuth",
                "ExtKeyUsageCodeSigning",
                "ExtKeyUsageEmailProtection",
                "ExtKeyUsageIPSECEndSystem",
                "ExtKeyUsageIPSECTunnel",
                "ExtKeyUsageIPSECUser",
                "ExtKeyUsageTimeStamping",
                "ExtKeyUsageOCSPSigning",
                "ExtKeyUsageMicrosoftServerGatedCrypto",
                "ExtKeyUsageNetscapeServerGatedCrypto",
                "ExtKeyUsageMicrosoftCommercialCodeSigning",
                "ExtKeyUsageMicrosoftKernelCodeSigning"
            ]
        },
        "x509.KeyUsage": {
            "type": "integer",
            "enum": [
                1,
                2,
                4,
                8,
                16,
                32,
                64,
                128,
                256
            ],
            "x-enum-varnames": [
                "KeyUsageDigitalSignature",
                "KeyUsageContentCommitment",
                "KeyUsageKeyEncipherment",
                "KeyUsageDataEncipherment",
                "KeyUsageKeyAgreement",
                "KeyUsageCertSign",
                "KeyUsageCRLSign",
                "KeyUsageEncipherOnly",
                "KeyUsageDecipherOnly"
            ]
        },
        "x509.OID": {
            "type": "object"
        },
        "x509.PolicyMapping": {
            "type": "object",
            "properties": {
                "issuerDomainPolicy": {
                    "description": "IssuerDomainPolicy contains a policy OID the issuing certificate considers\nequivalent to SubjectDomainPolicy in the subject certificate.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/x509.OID"
                        }
                    ]
                },
                "subjectDomainPolicy": {
                    "description": "SubjectDomainPolicy contains a OID the issuing certificate considers\nequivalent to IssuerDomainPolicy in the subject certificate.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/x509.OID"
                        }
                    ]
                }
            }
        },
        "x509.PublicKeyAlgorithm": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-comments": {
                "DSA": "Only supported for parsing."
            },
            "x-enum-varnames": [
                "UnknownPublicKeyAlgorithm",
                "RSA",
                "DSA",
                "ECDSA",
                "Ed25519"
            ]
        },
        "x509.SignatureAlgorithm": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16
            ],
            "x-enum-comments": {
                "DSAWithSHA1": "Unsupported.",
                "DSAWithSHA256": "Unsupported.",
                "ECDSAWithSHA1": "Only supported for signing, and verification of CRLs, CSRs, and OCSP responses.",
                "MD2WithRSA": "Unsupported.",
                "MD5WithRSA": "Only supported for signing, not verification.",
                "SHA1WithRSA": "Only supported for signing, and verification of CRLs, CSRs, and OCSP responses."
            },
            "x-enum-varnames": [
                "UnknownSignatureAlgorithm",
                "MD2WithRSA",
                "MD5WithRSA",
                "SHA1WithRSA",
                "SHA256WithRSA",
                "SHA384WithRSA",
                "SHA512WithRSA",
                "DSAWithSHA1",
                "DSAWithSHA256",
                "ECDSAWithSHA1",
                "ECDSAWithSHA256",
                "ECDSAWithSHA384",
                "ECDSAWithSHA512",
                "SHA256WithRSAPSS",
                "SHA384WithRSAPSS",
                "SHA512WithRSAPSS",
                "PureEd25519"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Odometer Attester API",
	Description:      "This is the API documentation for the Odometer Attester service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
