replicaCount: 1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
bridge:
  image:
    repository: dimozone/enclave-bridge
    pullPolicy: IfNotPresent
    tag: 0.0.1
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  env:
    LOG_LEVEL: DEBUG
    PORT: '8080'
    MON_PORT: '8888'
    VSOCK_INIT_PORT: '5000'
    VEHICLE_NFT_CONTRACT_ADDRESS: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
    DEVELOPER_LICENSE: '0xd848A3f7501979069E1DBC17f366379f34187EA6'
    DEX_URL: https://auth.dimo.zone
    IDENTITY_API_URL: https://identity-api.dimo.zone
    TELEMETRY_API_URL: https://telemetry-api.dimo.zone
    TOKEN_EXCHANGE_URL: https://token-exchange.dimo.zone
    DEV_FAKE_KEY: 073564dcc1a9745fef22ac023b635604dc7c3dda2b84165b7eff5ccd68d48fe7
  ports:
    - name: mon-http
      containerPort: 8888
      protocol: TCP
    - name: http
      containerPort: 8080
      protocol: TCP
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
app:
  image:
    repository: dimozone/odometer-attester-enclave
    pullPolicy: IfNotPresent
    tag: bfafb96
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  env:
    ENCLAVE_CPU_COUNT: '2'
    ENCLAVE_MEMORY_SIZE: '1000'
    ENCLAVE_CID: '16'
    ENCLAVE_DEBUG_MODE: null
  ports: null
  resources:
    limits:
      aws.ec2.nitro/nitro_enclaves: '1'
      hugepages-1Gi: 1Gi
      memory: 512Mi
      cpu: 500m
    requests:
      aws.ec2.nitro/nitro_enclaves: '1'
      hugepages-1Gi: 1Gi
      memory: 128Mi
      cpu: 100m
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone, https://admin.team.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '50'
    external-dns.alpha.kubernetes.io/hostname: odometer-attester.dev.dimo.zone
  hosts:
    - host: odometer-attester.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector:
  enclave: 'true'
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics: []
serviceAccount:
  create: true
  annotations: {}
  name: ''
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
secrets:
  enabled: false
